export interface PercetpaSettings {
  K_HEAD: number;
  DEAD_ZONE: number;
  ALPHA: number;
  SMOOTH_WINDOW: number;
  EYEBROW_THRESHOLD: number;
  CLICK_COOLDOWN: number;
  GESTURE_CONFIDENCE_THRESHOLD: number;
  GESTURE_COOLDOWN: number;
  TARGET_FPS: number;
  FACE_CONFIDENCE_THRESHOLD: number;
  VOICE_CONFIDENCE_THRESHOLD: number;
}

export const DEFAULT_SETTINGS: PercetpaSettings = {
  K_HEAD: 3.0,
  DEAD_ZONE: 4,
  ALPHA: 0.35,
  SMOOTH_WINDOW: 5,
  EYEBROW_THRESHOLD: 0.22,
  CLICK_COOLDOWN: 0.8,
  GESTURE_CONFIDENCE_THRESHOLD: 0.65,
  GESTURE_COOLDOWN: 0.5,
  TARGET_FPS: 20,
  FACE_CONFIDENCE_THRESHOLD: 0.5,
  VOICE_CONFIDENCE_THRESHOLD: 0.8
};
