import { RefCallback } from 'react';
import DashboardPanel from '../components/DashboardPanel';
import { usePerceptionStore } from '../store/perceptionStore';
import { useEventStore } from '../store/eventStore';
import { useSystemStore } from '../store/systemStore';

function confidence(value: number) { return `${Math.round(value * 100)}%`; }
function SensorCard({ name, state, gesture, value, detail, enabled }: { name: string; state: string; gesture: string; value: number; detail: string; enabled: boolean }) {
  return <article className={`sensor-card ${enabled ? 'enabled' : 'disabled'}`}><div className="sensor-top"><span className="sensor-name">{name}</span><span className="live-tag"><i className={`status-dot ${enabled ? 'active' : 'error'}`} /> {enabled ? state : 'DISABLED'}</span></div><strong className="gesture-state">{enabled ? gesture || 'NO SIGNAL' : 'MODALITY OFF'}</strong><div className="confidence-row"><span>CONFIDENCE</span><span>{enabled ? confidence(value) : '—'}</span></div><div className="confidence-bar"><div className="confidence-fill" style={{ width: `${enabled ? value * 100 : 0}%` }} /></div><small>{enabled ? detail : 'Enable this modality to resume local inference.'}</small></article>;
}

export default function Dashboard({ videoRef }: { videoRef: RefCallback<HTMLVideoElement> }) {
  const { face, hand, faceEnabled, handEnabled, voiceEnabled, multiUserDetected, trackingLocked } = usePerceptionStore();
  const enabledModalities: Record<string, boolean> = { FACE: faceEnabled, HAND: handEnabled, VOICE: voiceEnabled };
  const events = useEventStore((state) => state.events).filter((event) => enabledModalities[event.modality] !== false).slice(-6).reverse();
  const { wsStatus, handModelLoaded, faceModelLoaded } = useSystemStore();
  return <div className="page dashboard-page"><div className="page-intro"><div><p className="eyebrow">SESSION / REAL-TIME</p><h2>Perceptual field</h2></div><span className={`connection-pill ${wsStatus}`}>{wsStatus === 'connected' ? '● LIVE INFERENCE' : `● ${wsStatus.toUpperCase()}`}</span></div>
    <div className="dashboard-grid"><DashboardPanel title="Sensor field" eyebrow="01 / CAMERA INPUT" className="camera-panel"><div className="camera-stage"><video ref={videoRef} muted playsInline /><div className="camera-grid" />{faceEnabled && face?.bbox && <span className="camera-bbox face-bbox" style={{ left: `${face.bbox.x / 6.4}%`, top: `${face.bbox.y / 4.8}%`, width: `${face.bbox.w / 6.4}%`, height: `${face.bbox.h / 4.8}%` }}><b>FACE</b></span>}{handEnabled && hand?.bbox && <span className="camera-bbox hand-bbox" style={{ left: `${hand.bbox.x / 6.4}%`, top: `${hand.bbox.y / 4.8}%`, width: `${hand.bbox.w / 6.4}%`, height: `${hand.bbox.h / 4.8}%` }}><b>HAND</b></span>}<div className="camera-empty">{(faceEnabled && face?.detected) || (handEnabled && hand?.detected) ? 'TRACKING ACTIVE' : 'ALLOW CAMERA TO BEGIN'}<small>Local HUD / enabled modalities only</small></div>{trackingLocked && faceEnabled && <span className="tracking-lock">ACTIVE USER / LOCKED</span>}{multiUserDetected && faceEnabled && <span className="multi-user">MULTIPLE USERS</span>}</div></DashboardPanel>
      <DashboardPanel title="Modality status" eyebrow="02 / NORMALIZED INPUTS" className="status-panel"><div className="sensor-list"><SensorCard enabled={faceEnabled} name="HEAD + FACE" state={face?.detected ? 'ACTIVE' : 'IDLE'} gesture={face?.gesture || 'WAITING'} value={face?.confidence || 0} detail={face?.head_pose ? `Δ ${face.head_pose.dx.toFixed(1)} / ${face.head_pose.dy.toFixed(1)} · tilt ${face.head_pose.tilt.toFixed(1)}°` : 'No face geometry received'} /><SensorCard enabled={handEnabled} name="HANDS" state={hand?.detected ? 'ACTIVE' : 'IDLE'} gesture={hand?.gesture || 'WAITING'} value={hand?.confidence || 0} detail={hand?.gesture_state || 'Temporal filter standing by'} /><SensorCard enabled={voiceEnabled} name="VOICE" state="BROWSER READY" gesture={events.find((event) => event.modality === 'VOICE')?.event_type || 'LISTENING'} value={events.find((event) => event.modality === 'VOICE')?.confidence || 0} detail="Speech commands normalize into events" /></div></DashboardPanel>
      <DashboardPanel title="Event stream" eyebrow="03 / EVENT BUS" className="events-panel"><div className="model-status"><span>FACE MODEL <b className={faceModelLoaded ? 'ok' : 'warn'}>{faceModelLoaded ? 'LOADED' : 'FALLBACK / UNAVAILABLE'}</b></span><span>HAND MODEL <b className={handModelLoaded ? 'ok' : 'warn'}>{handModelLoaded ? 'LOADED' : 'NOT AVAILABLE'}</b></span></div><div className="event-list">{events.length ? events.map((event) => <div className="event-row" key={event.id}><time>{event.formatted_time}</time><b>{event.event_type}</b><span>{event.modality}</span><em>{confidence(event.confidence)}</em></div>) : <div className="empty-state">No events yet. Start the camera or speak a command to populate the stream.</div>}</div></DashboardPanel>
    </div></div>;
}
